---
- name: "Install build deps for Python tools"
  apt:
    name:
      - build-essential
      - python3-dev
      - libssl-dev
      - pkg-config
      - rustc
      - cargo
    state: present
  become: true

  
- name: "Install pipx tools"
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.url }}"
    state: latest
  loop:
    - { name: 'impacket', url: 'git+https://github.com/fortra/impacket.git' }
    - { name: 'netexec', url: 'git+https://github.com/Pennyw0rth/NetExec.git' }
    - { name: 'certipy-ad', url: 'git+https://github.com/ly4k/Certipy.git' }
    - { name: 'bloodhound-ce', url: 'git+https://github.com/dirkjanm/BloodHound.py.git@bloodhound-ce' }
